spring:
  datasource:
    url: jdbc:postgresql://staging-db-host:5432/school
    username: staging_user
    password: staging_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  data:
    mongodb:
      uri: mongodb://staging-mongo-host:27017/school

server:
  port: 8081
