spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: P@ssw0rd1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://localhost:27017/school

server:
  port: 8080
