spring:
  application:
    name: student-crud-service

  profiles:
    active: default

  docker:
    compose:
      enabled: false

  security:
    user:
      name: ${APP_USERNAME:admin}
      password: ${APP_PASSWORD:password}

  datasource:
    url: jdbc:postgresql://localhost:5432/school
    username: postgres
    password: P@ssw0rd1
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  data:
    mongodb:
      uri: mongodb://localhost:27017/school

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080

api:
  base-path: /api