spring:
  application:
    name: student-crud-service

  profiles:
    active: default

  security:
    user:
      name: ${APP_USERNAME:admin}
      password: ${APP_PASSWORD:password}

  datasource:
    url: jdbc:postgresql://postgres:5432/school
    username: postgres
    password: P@ssw0rd1
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    mongodb:
      uri: mongodb://mongo:27017/school

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

server:
  port: 8080

api:
  base-path: /api